version: "3"

services: 
  app:
    build: .
    container_name: laike-travel-voucher
    restart: always
    tty: true
    networks: 
      - laike-travel-voucher_bridge
    ports: 
      - 9000:3000
      - 9229:9229
    volumes: 
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      NODE_ENV: development
    depends_on: 
      - db

  db:
    image: mongo:latest
    container_name: laike-travel-voucher_db
    networks:
      - laike-travel-voucher_bridge
    volumes:
      - ./db-mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: laike-travel-voucher_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks: 
  laike-travel-voucher_bridge:
    driver: bridge
